import AppBar from "@/components/appBar";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// 일반체 폰트 로드
const nanumSquareRegular = localFont({
  src: "./fonts/NanumSquareR.ttf",
  variable: "--font-nanum-square-regular",
  preload: false,
});

// 볼드체 폰트 로드
const nanumSquareBold = localFont({
  src: "./fonts/NanumSquareB.ttf",
  variable: "--font-nanum-square-bold",
  preload: false,
});

// favicon 설정
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nanumSquareRegular.variable} ${nanumSquareBold.variable} antialiased`}
      >
        <div className="mx-auto my-2 flex min-h-screen max-w-screen-lg flex-col items-center justify-start gap-4 font-nanumSquareBold text-[16px]">
          <AppBar />
          {children}
        </div>
      </body>
    </html>
  );
}
