import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const nanumSquareRegular = localFont({
    src: './fonts/NanumSquareR.ttf',
    variable: '--font-nanum-square-regular',
});

const nanumSquareBold = localFont({
    src: './fonts/NanumSquareB.ttf',
    variable: '--font-nanum-square-bold',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    icons: {
        icon: '/images/favicon.svg',
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    console.log(nanumSquareBold);
    return (
        <html lang="en">
            <body
                className={`${nanumSquareRegular.variable} ${nanumSquareBold.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
